apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: registry
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 12Gi
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
