apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: django-vault-secrets
  namespace: django-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: django-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: django-app/database
        property: DB_NAME
    - secretKey: DB_USER
      remoteRef:
        key: django-app/database
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: django-app/database
        property: DB_PASSWORD
    - secretKey: SECRET_KEY
      remoteRef:
        key: django-app/database
        property: SECRET_KEY
